version: '3'

services:
  app:
    build: .  # Ссылка на Dockerfile
#    links:  # Связывает контейнеры между собой
#      - db
    ports:
      - "8080:5000"
#    depends_on:
#      - db

#  db:
#    image: postgres:10.4
#    restart: always
#    env_file: .env
#    ports:
#      - "8000:8000"
#    volumes:
#      - /home/sskey/db
